### ISSUE TITLE
Refact in react

### ISSUE THREAD

**Issue by felipebrunetti94** [MEHDI-ROBATJAZI/RCG-PROJECT#3]
Refact the code in react app.

**Comment by MEHDI-ROBATJAZI** [comment]
Thank you for contributing .I'm learning REACT right now, you can go on

_THANK YOU._

**Comment by felipebrunetti94** [comment]
I'll refact the code into a React app, if you have any question just message me.

**Comment by MEHDI-ROBATJAZI** [comment]
I'm learning these changes but can't run the program
can you help me ?

**Comment by felipebrunetti94** [comment]
Sure, you have to use npm start to run the project. It's still incomplete, i need to implement the buttons, but the circles are ready.  If you have any doubt or just need help, just message me. :D

**Comment by MEHDI-ROBATJAZI** [comment]
![Annotation 2019-10-26 150429](https://user-images.githubusercontent.com/43264216/67626632-bf9ef700-f802-11e9-8abc-687e835b089a.png)


this is my problem

**Comment by felipebrunetti94** [comment]
okay, first you have a typo in the first line, there is an 'n' in the beginning.
Second, do you have node install ?
Third, do you konw how to use the terminal ?

Fourth, my bad kk I forgot to move the jason file to the main folder, I'll fix it right now.

**Comment by felipebrunetti94** [comment]
Try it now :D
